# -*- coding: utf-8 -*-
"""FakeNewsDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qF8VyCCJ1A1pv3byW07F1NYNj_TLMyQs
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
import itertools
from sklearn.feature_extraction.text import TfidfVectorizer
import csv

"""Uses python parser (slow parsing) instead of C parser used by pandas forgiving with messy formatting"""

df=pd.read_csv("/content/news.csv",engine='python',on_bad_lines='skip')

df.shape

df.info()

df.isna().value_counts()

"""There are no null values in dataset"""

df.head()

"""Manually coding train test split"""

from numpy._core.multiarray import ndarray
def train_test_split_manual(x_val,y_val,test_size,seed):
  # try:
  if isinstance(x_val,(pd.DataFrame,pd.Series)) and isinstance(y_val,(pd.DataFrame,pd.Series))==True:
    #merge and resample
    #frac=1 since we are considering whole dataframe
    randomised_df=pd.concat([x_val,y_val],axis=1).sample(frac=1,random_state=seed)
    #split
    slice_val=(int)(len(randomised_df)*test_size) #100*0.2=20 ; slice at 20
    #create train and test set
    train_set,test_set=randomised_df[slice_val:],randomised_df[:slice_val]

  elif isinstance(x_val,(np.ndarray,list)) and isinstance(y_val,(np.ndarray,list))==True:
    #merge and resample
    randomised_df=pd.concat([pd.DataFrame(x_val),pd.DataFrame(y_val)],axis=1).sample(frac=1,random_state=seed)
    #split
    slice_val=(int)(len(randomised_df)*test_size) #100*0.2=20 ; slice at 20
    #create train and test set
    train_set,test_set=randomised_df[slice_val:],randomised_df[:slice_val]

  #return x,y of train test x=features y=label
  return train_set.iloc[:,:-1],train_set.iloc[:,-1],test_set.iloc[:,:-1],test_set.iloc[:,-1]

  # except:
  #     print("X and Y must be of same type")

slice_val=(int)(len(df)*0.2)
slice_val

df_iris=pd.read_csv("/content/Iris.csv")

df_iris.head()

X=df_iris.iloc[:,1:5].values
y=df_iris.iloc[:,-1].values

train_test_split_manual(X,y,0.2,42)[3]

""" train test split"""

X=df.iloc[:,2].values
y=df.iloc[:,-1].values
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# X[:2,1] array is 1-dimensional, but 2 were indexed

# y[2:,1] array is 1-dimensional, but 2 were indexed

type(X)

type(y)

"""stop_words='english' removes stopwords

max_df:
In this case, setting max_df
to a higher value, such as in the range (0.7, 1.0), can automatically detect
and filter stop words based on intra corpus document frequency of terms.
"""

vectorizer=TfidfVectorizer(stop_words='english',max_df=0.7)
tfidf_train=vectorizer.fit_transform(X_train)

tfidf_test=vectorizer.transform(X_test)

pac=PassiveAggressiveClassifier(max_iter=50)
pac.fit(tfidf_train,y_train)
y_pred=pac.predict(tfidf_test)

"""Evaluating model"""

score=accuracy_score(y_test,y_pred)
print("Accuracy Score: ",(round(score*100,2)),"%")
print(f"Accuracy Score: {round(score*100,2)}%")

confusion_matrix(y_test,y_pred,labels=['FAKE','REAL'])

"""
True positive:588, False negative:40 ,False positive:43 , True Negative:596"""